# Generated by Django 5.1.5 on 2025-01-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='updated_at',
        ),
    ]
